server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/productdb
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: PRODUCT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
  zipkin:
    base-url: ${ZIPKIN_URL:http://localhost:9411}
zipkin:
  sender:
    baseUrl:${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
management:
  tracing:
    sampling:
      probability: 1.0
#eureka:
  #instance:
    #prefer-ip-address: true
  #client:
    #fetch-registry: true
    #register-with-eureka: true
    #service-url:
      #defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
