server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/paymentdb
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: PAYMENT-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}
      #eureka:
      #instance:
      #prefer-ip-address: true
      #client:
      #fetch-registry: true
      #register-with-eureka: true
      #service-url:
      #defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka/}
