server:
  port: 8085

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/identitydb
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:1234}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  application:
    name: IDENTITY-SERVICE
  config:
    import: configserver:${CONFIG_SERVER_URL:http://localhost:9296}

management:
  metrics:
    export:
      zipkin:
        baseUrl: ${ZIPKIN_URL:http://localhost:9411}/api/v2/spans
        enabled: true
  tracing:
    brave:
      enabled: true
      sampler:
        rate: 1.0
      spans:
        compression-enabled: true